server:
  port: 8081
spring:
  application:
    name: "technologies"
  devtools:
    add-properties: false
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/capacity?currentSchema=public"
    username: "postgres"
    password: "1234"
  sql:
    init:
      mode: "always"
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
